### ISSUE TITLE
Add Certifications section

### ISSUE THREAD

**Issue by amar-preet** [slalom/profiles#1]
Create a new section Certifications below Skills. User should be able to enter the certification they have and it should add the icon for that certification.

**Comment by ssieng-slalom** [comment]
Certification section has been added with the latest pull request but the icon is still missing, we should probably separate that into a different issue as the official template doesn't suggest the icon but having an icon for certification is definitely nice to have feature so I want to treat that icons as enhancement while treat missing certification section as issue.

**Comment by ssieng-slalom** [comment]
Close as we will track for the requests in Slalom Norcal Jira.
