### ISSUE TITLE
Text Overlapping with Footer on Main Page

### ISSUE THREAD

**Issue by amar-preet** [slalom/profiles#2]
There is a layout issue on the main page where the body text overlaps with the footer section. This issue affects the readability of the content and disrupts the intended page layout.

**Comment by HimanshuDTU18** [comment]
can you assign this to me?

**Comment by ssieng-slalom** [comment]
> can you assign this to me?

Sorry, although this project is public but it belongs to Slalom which is private organization so we can't assign the issue to someone outside of Slalom.

**Comment by ssieng-slalom** [comment]
The issue should have been fixed in with the latest pull request.
